name: Build base.xlsx

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 6 * * *"  # ежедневно в 06:00 UTC

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r automation/requirements.txt

      - name: Build base.xlsx (inside /automation)
        working-directory: automation
        run: |
          python make_base_auto.py
          test -s base.xlsx

      - name: Move result to repo root
        run: mv -f automation/base.xlsx ./base.xlsx

      - name: Commit if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add base.xlsx
          if git diff --cached --quiet; then
            echo "No changes."
            exit 0
          fi
          git commit -m "auto: update base.xlsx"
          git push
